
port: 7890
allow-lan: false
mode: rule
log-level: silent
ipv6: true

proxies:
  - name: LIMITLESS STREAMING GP
    type: vmess
    server: 68.233.115.38
    port: 4442
    uuid: 11c6fd2e-02df-4157-b61b-11e7cf474b23
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"
  
  - name: LIMITLESS SOCIAL GP
    type: vmess
    server: 68.233.115.38
    port: 4442
    uuid: 11c6fd2e-02df-4157-b61b-11e7cf474b23
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"
  
  - name: LIMITLESS STREAMING ROBI
    type: vmess
    server: 68.233.115.38
    port: 4442
    uuid: 11c6fd2e-02df-4157-b61b-11e7cf474b23
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"

  - name: LIMITLESS STREEAMING BL
    type: vmess
    server: 68.233.115.38
    port: 4442
    uuid: 11c6fd2e-02df-4157-b61b-11e7cf474b23
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"
        
proxy-groups:
  - name: BDCLOUD-GIVEWAY
    type: select
    proxies:
      - DIRECT
      - LIMITLESS STREAMING GP
      - LIMITLESS SOCIAL GP
      - LIMITLESS STREAMING ROBI
      - LIMITLESS STREEAMING BL

rules:
  #  - SCRIPT,NULLDNS,REJECT 
  - IP-CIDR,0.0.0.0/32,REJECT #PATCH FOR  META AND PREMIUM CLASH
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - DOMAIN-SUFFIX,ad.com,REJECT
  - DOMAIN,analytics.google.com,REJECT
  - DOMAIN,analyticsinsights-pa.googleapis.com,REJECT
  - DOMAIN,analyticsreporting.googleapis.com,REJECT
  - DOMAIN-SUFFIX,doubleclick.net,REJECT
  - DOMAIN-SUFFIX,googleadservices.com,REJECT
  - DOMAIN-SUFFIX,googleadsserving.cn,REJECT
  - DOMAIN-SUFFIX,googlesyndication.com,REJECT
  - DOMAIN-SUFFIX,googletagmanager.com,REJECT
  - DOMAIN-SUFFIX,googletagservices.com,REJECT
  - DOMAIN-SUFFIX,google-analytics.com,REJECT
  - IP-CIDR,172.16.50.7/24,BDCLOUD-GIVEWAY
  - MATCH,BDCLOUD-GIVEWAY
